### PR TITLE
Added documentation for plugin option --importConfig

### PR DESCRIPTION
**Pull request by jenow**

### CODE REVIEW

**Comment by scottinet** [comment]
Already added it in the plugins documentation refactor (KUZ-593).

Considering how painful it is to merge documentation pull requests, can we close this one? :-)

**Comment by jenow** [comment]
Oh ok! where can I see it?

**Comment by scottinet** [comment]
I pushed the branch just now so you can check how I documented it, but this is still work in progress:
https://github.com/kuzzleio/kuzzle-guide/tree/kuz-593-refactor-plugins-documentation

**Comment by jenow** [comment]
Perfect, I'm closing this PR then.

**Pull request closed without merging**
