### PR TITLE
fix #10: missing geolocation images

### LINKED ISSUE #10: Issue related to "User guide/Filtering Syntax/Geospacial" section
Missing illustrations

### PR DESCRIPTION
**Pull request by scottinet**
- fixes issue #10: retrieved missing images from an old kuzzle branch and fixed images links
- moved the `Geospatial` section at the beginning of this sub-guide, as it explains how geospatial filters work. This way, it keeps the documentation homogeneous (some explanation sections followed by a filter keywords rundown)
- "warning" blocks about latitude-longitude arguments order have been demoted to "note" blocks
- fixed external links inside "note" blocks
- promoted geospatial filtering functions to subsections, in order to make them visible in the menu bar
- reworded many filtering functions explanations

### CODE REVIEW

**Comment by stafyniaksacha** [comment]
+1

**Comment by ballinette** [comment]
It's quite disturbing to see the documentation of geospatial functions splitted btw. the beginning of the section (and without the graphics), and the end.
I understand that both parts are not equivalents, but, ihmo:
* we should keep main / most used filters in the beginning of the section
* description of geospatial filters should follow the main documentation of this sub-section.

I understand the need of making  geospatial filtering functions visible in the menu, but we can do it like for the plugins' documentation (I agree, it's not really clean, but it works ;)):
http://kuzzle.io/guide/#plugins
https://github.com/kuzzleio/kuzzle-guide/blob/develop/source/includes/core_documentation/_04-plugins.md
See section "Events triggered", followed by each event types, prefixed by ">"

In the same way, we could have a TOC for filtering syntax like that:
* Filtering Syntax
  * "Main" filters _(or find a better wording)_
  * > and
  * > bool
  * > (etc.)
  * Geospatial filters
  * > geoBoundingBox
  * > geoDistance
  * > geoDistanceRange
  * > geoPolygon

**Comment by scottinet** [comment]
I actually like your suggestion. I'll implement it right away.

**Comment by scottinet** [comment]
@ballinette > I propose this menu content, what do you think of it?

* Filtering Syntax
  * Filtering terms
  * > exists
  * > missing
  * > not
  * > term
  * > terms
  * > ids
  * > range
  * Regrouping filter terms
  * > and
  * > bool
  * > or
  * Geospatial filters
  * > geoBoundingBox
  * > geoDistance
  * > geoDistanceRange
  * > geoPolygon

**Comment by ballinette** [comment]
@scottinet it looks good ;)

**Comment by scottinet** [comment]
Done!

**Comment by ballinette** [comment]
nice, +1

**Pull request merged**
